"""initial schema baseline

Revision ID: bcbf89d1e8f9
Revises: 
Create Date: 2026-10-07 00:39:41.895744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbf89d1e8f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias_bien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias_carta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas_turisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruta', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'ip', name='uq_login_attempt_username_ip')
    )
    op.create_index('ix_login_attempts_window', 'login_attempts', ['ventana_inicio'], unique=False)
    op.create_table('productos_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=150), nullable=True),
    sa.Column('proveedor_tel', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index('ix_auditoria_fecha', ['fecha_hora'], unique=False)
        batch_op.create_index('ix_auditoria_tabla', ['tabla'], unique=False)

    op.create_table('balones_gas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=120), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('dias_uso', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bienes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('estado_bueno', sa.Integer(), nullable=True),
    sa.Column('estado_malo', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_bien.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cierres_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cerrado_por', sa.Integer(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('efectivo', sa.Float(), nullable=True),
    sa.Column('tarjeta', sa.Float(), nullable=True),
    sa.Column('yape', sa.Float(), nullable=True),
    sa.Column('transferencia', sa.Float(), nullable=True),
    sa.Column('total_cobrado', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=150), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=30), nullable=True),
    sa.Column('serie_comprobante', sa.String(length=20), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=30), nullable=True),
    sa.Column('archivo_comprobante', sa.String(length=255), nullable=True),
    sa.Column('tipo_pago', sa.String(length=30), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('numero_operacion', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('igv', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.create_index('ix_compras_estado', ['estado'], unique=False)
        batch_op.create_index('ix_compras_fecha', ['fecha'], unique=False)

    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=5), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=True),
    sa.Column('sueldo_base', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('entregas_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_recurrentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'fecha', name='uq_entrega_producto_dia')
    )
    with op.batch_alter_table('entregas_diarias', schema=None) as batch_op:
        batch_op.create_index('ix_entregas_prod_fecha', ['producto_id', 'fecha'], unique=False)

    op.create_table('listas_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo_requerimiento', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('elaborado_por_id', sa.Integer(), nullable=False),
    sa.Column('elaborado_en', sa.DateTime(), nullable=True),
    sa.Column('verificado_por_id', sa.Integer(), nullable=True),
    sa.Column('verificado_en', sa.DateTime(), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['elaborado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['verificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listas_pedido', schema=None) as batch_op:
        batch_op.create_index('ix_pedidos_estado_fecha', ['estado', 'elaborado_en'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=30), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index('ix_notif_dest_leido', ['destinatario_id', 'leido'], unique=False)

    op.create_table('pagos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=False),
    sa.Column('periodo_hasta', sa.Date(), nullable=False),
    sa.Column('cantidad_total', sa.Float(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('monto_pagado', sa.Float(), nullable=True),
    sa.Column('tipo_pago', sa.String(length=30), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('archivo_voucher', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_recurrentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.create_index('ix_pagos_prov_prod', ['producto_id'], unique=False)

    op.create_table('permisos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso', sa.String(length=50), nullable=False),
    sa.Column('otorgado_por', sa.Integer(), nullable=True),
    sa.Column('otorgado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['otorgado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'permiso', name='uq_permiso_usuario')
    )
    with op.batch_alter_table('permisos_usuario', schema=None) as batch_op:
        batch_op.create_index('ix_permisos_usuario', ['usuario_id'], unique=False)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index('ix_productos_categoria_activo', ['categoria_id', 'activo'], unique=False)

    op.create_table('registro_pasajeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre_grupo', sa.String(length=120), nullable=True),
    sa.Column('num_pax', sa.Integer(), nullable=True),
    sa.Column('precio_buffet', sa.Float(), nullable=True),
    sa.Column('ruta', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas_turisticas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_pasajeros', schema=None) as batch_op:
        batch_op.create_index('ix_pasajeros_fecha', ['fecha'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('nombre_grupo', sa.String(length=150), nullable=True),
    sa.Column('num_pax', sa.Integer(), nullable=True),
    sa.Column('precio_buffet', sa.Float(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('alerta_vista', sa.Boolean(), nullable=True),
    sa.Column('numero_file', sa.String(length=80), nullable=True),
    sa.Column('empresa_libre', sa.String(length=150), nullable=True),
    sa.Column('monto_anticipado', sa.Float(), nullable=True),
    sa.Column('saldo_pendiente', sa.Float(), nullable=True),
    sa.Column('tipo_pago', sa.String(length=30), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('archivo_voucher', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas_turisticas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index('ix_reservas_estado', ['estado'], unique=False)
        batch_op.create_index('ix_reservas_estado_fecha', ['estado', 'fecha'], unique=False)
        batch_op.create_index('ix_reservas_fecha', ['fecha'], unique=False)

    op.create_table('ventas_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=True),
    sa.Column('nombre_grupo', sa.String(length=150), nullable=True),
    sa.Column('num_pax', sa.Integer(), nullable=True),
    sa.Column('ruta', sa.String(length=50), nullable=True),
    sa.Column('precio_buffet', sa.Float(), nullable=True),
    sa.Column('es_privado', sa.Boolean(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('tipo_pago', sa.String(length=30), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=30), nullable=True),
    sa.Column('serie_comprobante', sa.String(length=20), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas_turisticas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas_diarias', schema=None) as batch_op:
        batch_op.create_index('ix_ventas_empresa', ['empresa_id'], unique=False)
        batch_op.create_index('ix_ventas_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_ventas_fecha_emp', ['fecha', 'empresa_id'], unique=False)

    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('hora_entrada', sa.String(length=10), nullable=True),
    sa.Column('hora_salida', sa.String(length=10), nullable=True),
    sa.Column('horas_extra', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'fecha', name='uq_asistencia_dia')
    )
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index('ix_asist_emp_fecha', ['empleado_id', 'fecha'], unique=False)
        batch_op.create_index('ix_asist_fecha', ['fecha'], unique=False)

    op.create_table('comprobantes_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=150), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funciones_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('funcion', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honorarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo_pago', sa.String(length=30), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('numero_recibo', sa.String(length=50), nullable=True),
    sa.Column('archivo_recibo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_compra', schema=None) as batch_op:
        batch_op.create_index('ix_items_compra_compra', ['compra_id'], unique=False)

    op.create_table('kardex_almacen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('cant_entrada', sa.Float(), nullable=True),
    sa.Column('precio_entrada', sa.Float(), nullable=True),
    sa.Column('total_entrada', sa.Float(), nullable=True),
    sa.Column('costo_conocido', sa.Boolean(), nullable=False),
    sa.Column('cant_salida', sa.Float(), nullable=True),
    sa.Column('precio_salida', sa.Float(), nullable=True),
    sa.Column('total_salida', sa.Float(), nullable=True),
    sa.Column('cant_saldo', sa.Float(), nullable=True),
    sa.Column('precio_saldo', sa.Float(), nullable=True),
    sa.Column('total_saldo', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kardex_almacen', schema=None) as batch_op:
        batch_op.create_index('ix_kardex_alm_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_kardex_alm_prod', ['producto_id'], unique=False)
        batch_op.create_index('ix_kardex_alm_prod_fecha', ['producto_id', 'fecha'], unique=False)

    op.create_table('kardex_bienes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('bien_nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('bueno_entrada', sa.Integer(), nullable=False),
    sa.Column('bueno_salida', sa.Integer(), nullable=False),
    sa.Column('malo_entrada', sa.Integer(), nullable=False),
    sa.Column('malo_salida', sa.Integer(), nullable=False),
    sa.Column('saldo_bueno', sa.Integer(), nullable=False),
    sa.Column('saldo_malo', sa.Integer(), nullable=False),
    sa.Column('saldo_total', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('valor_ajuste', sa.Float(), nullable=True),
    sa.Column('valor_saldo', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bien_id'], ['bienes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kardex_bienes', schema=None) as batch_op:
        batch_op.create_index('ix_kardex_bien_prod_fecha', ['bien_id', 'fecha'], unique=False)

    op.create_table('movimientos_almacen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('lista_pedido_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lista_pedido_id'], ['listas_pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_almacen', schema=None) as batch_op:
        batch_op.create_index('ix_movimientos_producto_fecha', ['producto_id', 'fecha_hora'], unique=False)
        batch_op.create_index('ix_movimientos_tipo_fecha', ['tipo', 'fecha_hora'], unique=False)

    op.create_table('productos_carta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tiene_variantes', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descuenta_inventario', sa.Boolean(), nullable=True),
    sa.Column('producto_almacen_id', sa.Integer(), nullable=True),
    sa.Column('es_vino', sa.Boolean(), nullable=True),
    sa.Column('copas_por_botella', sa.Integer(), nullable=True),
    sa.Column('precio_copa', sa.Float(), nullable=True),
    sa.Column('precio_botella', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_carta.id'], ),
    sa.ForeignKeyConstraint(['producto_almacen_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asistencia_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('campo_cambiado', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.String(length=100), nullable=True),
    sa.Column('valor_nuevo', sa.String(length=100), nullable=True),
    sa.Column('justificacion', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asistencia_id'], ['asistencias.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('botellas_abiertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_carta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('copas_servidas', sa.Integer(), nullable=True),
    sa.Column('cerrada', sa.Boolean(), nullable=True),
    sa.Column('cerrada_en', sa.DateTime(), nullable=True),
    sa.Column('cerrada_por_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cerrada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_carta_id'], ['productos_carta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_vinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_carta_id', sa.Integer(), nullable=False),
    sa.Column('copas_por_botella', sa.Integer(), nullable=True),
    sa.Column('precio_copa', sa.Float(), nullable=True),
    sa.Column('precio_botella', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_carta_id'], ['productos_carta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_carta_id')
    )
    op.create_table('items_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('producto_nombre', sa.String(length=150), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=30), nullable=True),
    sa.Column('cantidad_solicitada', sa.Float(), nullable=True),
    sa.Column('cantidad_recibida', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes_pedido.id'], ),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kardex_comedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_carta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('cant_entrada', sa.Float(), nullable=True),
    sa.Column('precio_entrada', sa.Float(), nullable=True),
    sa.Column('total_entrada', sa.Float(), nullable=True),
    sa.Column('cant_salida', sa.Float(), nullable=True),
    sa.Column('precio_salida', sa.Float(), nullable=True),
    sa.Column('total_salida', sa.Float(), nullable=True),
    sa.Column('cant_saldo', sa.Float(), nullable=True),
    sa.Column('precio_saldo', sa.Float(), nullable=True),
    sa.Column('total_saldo', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_carta_id'], ['productos_carta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kardex_comedor', schema=None) as batch_op:
        batch_op.create_index('ix_kardex_com_prod', ['producto_carta_id'], unique=False)

    op.create_table('registros_botella',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_carta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('copas_vendidas', sa.Integer(), nullable=True),
    sa.Column('botellas_abiertas', sa.Integer(), nullable=True),
    sa.Column('botellas_vendidas_enteras', sa.Integer(), nullable=True),
    sa.Column('botella_vacia', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('confirmado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_carta_id'], ['productos_carta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantes_carta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_carta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_carta_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_carta_id'], ['productos_carta.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_carta.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_diarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_venta', schema=None) as batch_op:
        batch_op.create_index('ix_items_venta_venta', ['venta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_venta', schema=None) as batch_op:
        batch_op.drop_index('ix_items_venta_venta')

    op.drop_table('items_venta')
    op.drop_table('variantes_carta')
    op.drop_table('registros_botella')
    with op.batch_alter_table('kardex_comedor', schema=None) as batch_op:
        batch_op.drop_index('ix_kardex_com_prod')

    op.drop_table('kardex_comedor')
    op.drop_table('items_pedido')
    op.drop_table('config_vinos')
    op.drop_table('botellas_abiertas')
    op.drop_table('auditoria_asistencia')
    op.drop_table('productos_carta')
    with op.batch_alter_table('movimientos_almacen', schema=None) as batch_op:
        batch_op.drop_index('ix_movimientos_tipo_fecha')
        batch_op.drop_index('ix_movimientos_producto_fecha')

    op.drop_table('movimientos_almacen')
    with op.batch_alter_table('kardex_bienes', schema=None) as batch_op:
        batch_op.drop_index('ix_kardex_bien_prod_fecha')

    op.drop_table('kardex_bienes')
    with op.batch_alter_table('kardex_almacen', schema=None) as batch_op:
        batch_op.drop_index('ix_kardex_alm_prod_fecha')
        batch_op.drop_index('ix_kardex_alm_prod')
        batch_op.drop_index('ix_kardex_alm_fecha')

    op.drop_table('kardex_almacen')
    with op.batch_alter_table('items_compra', schema=None) as batch_op:
        batch_op.drop_index('ix_items_compra_compra')

    op.drop_table('items_compra')
    op.drop_table('honorarios')
    op.drop_table('funciones_diarias')
    op.drop_table('comprobantes_pedido')
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index('ix_asist_fecha')
        batch_op.drop_index('ix_asist_emp_fecha')

    op.drop_table('asistencias')
    with op.batch_alter_table('ventas_diarias', schema=None) as batch_op:
        batch_op.drop_index('ix_ventas_fecha_emp')
        batch_op.drop_index('ix_ventas_fecha')
        batch_op.drop_index('ix_ventas_empresa')

    op.drop_table('ventas_diarias')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index('ix_reservas_fecha')
        batch_op.drop_index('ix_reservas_estado_fecha')
        batch_op.drop_index('ix_reservas_estado')

    op.drop_table('reservas')
    with op.batch_alter_table('registro_pasajeros', schema=None) as batch_op:
        batch_op.drop_index('ix_pasajeros_fecha')

    op.drop_table('registro_pasajeros')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index('ix_productos_categoria_activo')

    op.drop_table('productos')
    with op.batch_alter_table('permisos_usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_permisos_usuario')

    op.drop_table('permisos_usuario')
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.drop_index('ix_pagos_prov_prod')

    op.drop_table('pagos_proveedor')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_dest_leido')

    op.drop_table('notificaciones')
    with op.batch_alter_table('listas_pedido', schema=None) as batch_op:
        batch_op.drop_index('ix_pedidos_estado_fecha')

    op.drop_table('listas_pedido')
    with op.batch_alter_table('entregas_diarias', schema=None) as batch_op:
        batch_op.drop_index('ix_entregas_prod_fecha')

    op.drop_table('entregas_diarias')
    op.drop_table('empleados')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_index('ix_compras_fecha')
        batch_op.drop_index('ix_compras_estado')

    op.drop_table('compras')
    op.drop_table('cierres_caja')
    op.drop_table('cierres_asistencia')
    op.drop_table('bienes')
    op.drop_table('balones_gas')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index('ix_auditoria_tabla')
        batch_op.drop_index('ix_auditoria_fecha')

    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('productos_recurrentes')
    op.drop_index('ix_login_attempts_window', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('empresas_turisticas')
    op.drop_table('categorias_carta')
    op.drop_table('categorias_bien')
    op.drop_table('categorias')
    # ### end Alembic commands ###
